# Test your FastAPI endpoints

###
POST http://127.0.0.1:8000/event
Content-Type: application/json

{
  "task_name": "GlycemiaLevelTask",
  "data": 180,
  "metadata": {
    "patient": "Mario Gotz",
    "diabetes_family_history": true
  }
}